# Copyright (c) 2026 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/config/compiler/compiler.gni")

assert(current_os == "win")
assert(is_msvc)

_sdk_version = getenv("WindowsSDKVersion")
_sdk_root = getenv("WindowsSdkDir")
_sdk_host_arch = "x64"
_sdk_bin = "$_sdk_root/bin/$_sdk_version/$_sdk_host_arch"
_sdk_metadata = "$_sdk_root/UnionMetadata/$_sdk_version"
_generated_dir = "$target_gen_dir/projection"
_winmd = "$root_out_dir/Matter.Windows.Controller.winmd"

action("generate_projection") {
  script = "generate_projection.py"
  sources = [ "Matter.Windows.Controller.idl" ]
  outputs = [
    _winmd,
    "$_generated_dir/module.g.cpp",
  ]
  args = [
    "--midlrt",
    rebase_path("$_sdk_bin/midlrt.exe", root_build_dir),
    "--cppwinrt",
    rebase_path("$_sdk_bin/cppwinrt.exe", root_build_dir),
    "--sdk-metadata",
    rebase_path(_sdk_metadata, root_build_dir),
    "--idl",
    rebase_path(sources[0], root_build_dir),
    "--winmd",
    rebase_path(_winmd, root_build_dir),
    "--generated",
    rebase_path(_generated_dir, root_build_dir),
  ]
}

config("component_config") {
  include_dirs = [
    ".",
    _generated_dir,
  ]
  cflags = [
    "/EHsc",
    "/GR",
    "/U_HAS_EXCEPTIONS",
    "/D_HAS_EXCEPTIONS=1",
  ]
}

shared_library("Matter.Windows.Controller") {
  output_name = "Matter.Windows.Controller"
  output_dir = root_out_dir
  sources = [
    "$_generated_dir/module.g.cpp",
    "//src/app/server-cluster/testing/EmptyProvider.cpp",
    "AttributePath.cpp",
    "AttributePath.h",
    "BleCommissioningParameters.h",
    "CommandPath.cpp",
    "CommandPath.h",
    "ControllerOptions.cpp",
    "ControllerOptions.h",
    "EventPath.cpp",
    "EventPath.h",
    "MatterController.cpp",
    "MatterController.h",
    "OnNetworkCommissioningParameters.cpp",
    "OnNetworkCommissioningParameters.h",
    "Projection.cpp",
    "ProjectionTypes.h",
    "TimedInteractionOptions.cpp",
    "TimedInteractionOptions.h",
    "module.def",
  ]
  configs += [ ":component_config" ]
  deps = [
    ":generate_projection",
    "//src/app/data-model-provider",
    "//src/controller",
    "//src/credentials:default_attestation_verifier",
    "//src/platform",
    "//src/platform/logging:default",
  ]
  libs = [ "WindowsApp.lib" ]
  ldflags = [ "/DEF:" + rebase_path("module.def", root_build_dir) ]
}
